<?php

class Error {
    const ERROR_FALTARON_PARAMETROS = 1;
    const ERROR_INESPERADO_CATCH = 2;
    const ERROR_DE_CONEXION_BD = 3;
    const ERROR_DATOS_ERRONEOS = 4;
    const ERROR_DATO_NO_INSERTADO_ACTUALIZADO_BD = 5;
    const WARN_LA_CONSULTA_NO_OBTUVO_RESULTADOS = 6;
}
